#!/usr/bin/env python3
"""Generate paper/tables/*.tex from results/paper_suite_summary.json.

This is the single link between a benchmark run and the numbers printed
in the paper: run `uv run sfdb benchmark` to produce
results/paper_suite_summary.json, then run this script to regenerate
the LaTeX tables the paper \\input{}s. Never hand-edit the generated
tables; edit this script instead.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SUMMARY_PATH = REPO_ROOT / "results" / "paper_suite_summary.json"
TABLES_DIR = REPO_ROOT / "paper" / "tables"

ENGINES = ("KnowledgeGraph", "SheafDatabase")


def _fmt(x: float) -> str:
    if x < 1:
        return f"{x:.4f}"
    if x < 100:
        return f"{x:.2f}"
    return f"{x:,.1f}"


def _ratio(kg: float, sfdb: float) -> str:
    if kg == 0:
        return "n/a"
    r = sfdb / kg
    if r >= 10:
        return f"{r:,.0f}\\times"
    return f"{r:.2f}\\times"


def generate_insert_table(summary: dict) -> str:
    rows = []
    for n_str in sorted(summary["insert"], key=int):
        n = int(n_str)
        stats = summary["insert"][n_str]
        kg_mean = stats.get("KnowledgeGraph", {}).get("mean", 0.0)
        sh_mean = stats.get("SheafDatabase", {}).get("mean", 0.0)
        rows.append(
            f"${n:,}$ & ${_fmt(kg_mean)}$ & ${_fmt(sh_mean)}$ & ${_ratio(kg_mean, sh_mean)}$ \\\\"
        )
    body = "\n".join(rows)
    return f"""% Auto-generated by scripts/generate_tables.py from results/paper_suite_summary.json
% Do not edit by hand.
\\begin{{table}}[htbp]
\\centering
\\caption{{Insert latency (mean over ten runs). Lower is better.
SFDB / KG ratio is annotated in the last column.}}
\\label{{tab:insert}}
\\begin{{tabular}}{{lrrr}}
\\toprule
Facts & KG (ms) & SFDB (ms) & Ratio \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""


QUERY_CLASS_LABELS = {
    "LOOKUP": "LOOKUP",
    "GLOBAL": "GLOBAL",
    "TEMPORAL": "TEMPORAL (bounded)",
    "TEMPORAL_UNBOUNDED": "TEMPORAL (unbounded)",
}


def generate_query_table(summary: dict) -> str:
    rows = []
    classes = ("LOOKUP", "GLOBAL", "TEMPORAL", "TEMPORAL_UNBOUNDED")
    for qclass in classes:
        label = QUERY_CLASS_LABELS[qclass]
        for n_str in sorted(summary["query"], key=int):
            n = int(n_str)
            entry = summary["query"][n_str].get(qclass)
            if entry is None:
                continue
            kg_mean = entry["stats"].get("KnowledgeGraph", {}).get("mean", 0.0)
            sh_mean = entry["stats"].get("SheafDatabase", {}).get("mean", 0.0)
            rows.append(
                f"{label} & ${n:,}$ & ${_fmt(kg_mean)}$ & ${_fmt(sh_mean)}$ & ${_ratio(kg_mean, sh_mean)}$ \\\\"
            )
        rows.append("\\midrule")
    if rows and rows[-1] == "\\midrule":
        rows.pop()
    body = "\n".join(rows)
    return f"""% Auto-generated by scripts/generate_tables.py from results/paper_suite_summary.json
% Do not edit by hand.
\\begin{{table}}[htbp]
\\centering
\\caption{{Query latency by class and scale (mean over ten runs). Lower is
better. Ratios are SFDB / KG.}}
\\label{{tab:query}}
\\begin{{tabular}}{{llrrr}}
\\toprule
Class & Facts & KG (ms) & SFDB (ms) & Ratio \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""


def generate_memory_table(summary: dict) -> str:
    rows = []
    mem = summary.get("insert_memory_bytes", {})
    for n_str in sorted(mem, key=int):
        n = int(n_str)
        kg_mb = mem[n_str].get("KnowledgeGraph", 0.0) / 1e6
        sh_mb = mem[n_str].get("SheafDatabase", 0.0) / 1e6
        ratio = f"{sh_mb / kg_mb:.2f}\\times" if kg_mb else "n/a"
        rows.append(f"${n:,}$ & ${kg_mb:.1f}$ & ${sh_mb:.1f}$ & ${ratio}$ \\\\")
    body = "\n".join(rows)
    return f"""% Auto-generated by scripts/generate_tables.py from results/paper_suite_summary.json
% Do not edit by hand.
\\begin{{table}}[htbp]
\\centering
\\caption{{Resident memory delta from inserting $N$ facts (mean over ten
runs). SFDB / KG ratio is annotated in the last column.}}
\\label{{tab:memory}}
\\begin{{tabular}}{{lrrr}}
\\toprule
Facts & KG (MB) & SFDB (MB) & Ratio \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""


def generate_verification_table(summary: dict) -> str:
    total = 0
    passed = 0
    for n_str, classes in summary["query"].items():
        for qclass, entry in classes.items():
            total += 1
            if entry["verified"]:
                passed += 1
    return f"""% Auto-generated by scripts/generate_tables.py from results/paper_suite_summary.json
% Do not edit by hand.
\\providecommand{{\\verifiedcount}}{{{passed}}}
\\providecommand{{\\verifiedtotal}}{{{total}}}
"""


def main() -> int:
    if not SUMMARY_PATH.exists():
        print(f"error: {SUMMARY_PATH} not found. Run `uv run sfdb benchmark` first.", file=sys.stderr)
        return 1

    summary = json.loads(SUMMARY_PATH.read_text())
    TABLES_DIR.mkdir(parents=True, exist_ok=True)

    (TABLES_DIR / "insert_latency.tex").write_text(generate_insert_table(summary))
    (TABLES_DIR / "query_latency.tex").write_text(generate_query_table(summary))
    (TABLES_DIR / "memory.tex").write_text(generate_memory_table(summary))
    (TABLES_DIR / "verification_counts.tex").write_text(generate_verification_table(summary))

    for name in ("insert_latency", "query_latency", "memory", "verification_counts"):
        print(f"Wrote {TABLES_DIR / f'{name}.tex'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
