#!/usr/bin/env python3
"""Generate paper/tables/*.tex from results/paper_suite_summary.json.

This is the single link between a benchmark run and the numbers printed
in the paper: run `uv run sfdb benchmark` to produce
results/paper_suite_summary.json, then run this script to regenerate
the LaTeX tables the paper \\input{}s. Never hand-edit the generated
tables; edit this script instead.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SUMMARY_PATH = REPO_ROOT / "results" / "paper_suite_summary.json"
REPRO_PATH = REPO_ROOT / "results" / "paper_suite_reproducibility.json"
TABLES_DIR = REPO_ROOT / "paper" / "tables"
GENERATED_DIR = REPO_ROOT / "paper" / "generated"

# KnowledgeGraphMem is the storage-layer control variant: identical
# reification and query logic to KnowledgeGraph, with dict indexes in
# place of the SQLite tables (see sfdb.kg.engine.MemoryIndexManager).
ENGINES = ("KnowledgeGraph", "KnowledgeGraphMem", "SheafDatabase")


def _fmt(x: float) -> str:
    if x < 1:
        return f"{x:.4f}"
    if x < 100:
        return f"{x:.2f}"
    return f"{x:,.1f}"


def _fmt_hw(x: float) -> str:
    """Format a 95% CI half-width compactly."""
    if x < 0.01:
        return f"{x:.3f}"
    if x < 1:
        return f"{x:.2f}"
    if x < 100:
        return f"{x:.1f}"
    return f"{x:,.0f}"


def _mean_ci(stats: dict) -> str:
    """Render mean with a 95% CI half-width, e.g. ``9.41 \\pm 0.12``."""
    mean = stats.get("mean", 0.0)
    hw = (stats.get("ci95_high", 0.0) - stats.get("ci95_low", 0.0)) / 2
    return f"{_fmt(mean)} \\pm {_fmt_hw(hw)}"


def _ratio(baseline: float, sfdb: float) -> str:
    if baseline == 0:
        return "n/a"
    r = sfdb / baseline
    if r >= 10:
        return f"{r:,.0f}\\times"
    return f"{r:.2f}\\times"


def generate_insert_table(summary: dict) -> str:
    rows = []
    for n_str in sorted(summary["insert"], key=int):
        n = int(n_str)
        stats = summary["insert"][n_str]
        kg = stats.get("KnowledgeGraph", {})
        kgm = stats.get("KnowledgeGraphMem", {})
        sh = stats.get("SheafDatabase", {})
        rows.append(
            f"${n:,}$ & ${_mean_ci(kg)}$ & ${_mean_ci(kgm)}$ & ${_mean_ci(sh)}$"
            f" & ${_ratio(kg.get('mean', 0.0), sh.get('mean', 0.0))}$ \\\\"
        )
    body = "\n".join(rows)
    return f"""% Auto-generated by scripts/generate_tables.py from results/paper_suite_summary.json
% Do not edit by hand.
\\begin{{table}}[htbp]
\\centering
\\caption{{Insert latency in ms (mean over ten runs $\\pm$ 95\\% CI
half-width). Lower is better. KG-mem is the storage-layer control; it
performs no write-through persistence, so its insert cost is not
comparable to the two write-through engines (see text). The ratio
column is SFDB\\,/\\,KG.}}
\\label{{tab:insert}}
\\begin{{tabular}}{{lrrrr}}
\\toprule
Facts & KG (ms) & KG-mem (ms) & SFDB (ms) & SFDB/KG \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""


QUERY_CLASS_LABELS = {
    "LOOKUP": "LOOKUP",
    "GLOBAL": "GLOBAL",
    "CONTEXT": "CONTEXT",
    "TEMPORAL": "TEMPORAL (bounded)",
    "TEMPORAL_UNBOUNDED": "TEMPORAL (unbounded)",
}


def generate_query_table(summary: dict) -> str:
    rows = []
    classes = ("LOOKUP", "GLOBAL", "CONTEXT", "TEMPORAL", "TEMPORAL_UNBOUNDED")
    for qclass in classes:
        label = QUERY_CLASS_LABELS[qclass]
        for n_str in sorted(summary["query"], key=int):
            n = int(n_str)
            entry = summary["query"][n_str].get(qclass)
            if entry is None:
                continue
            kg = entry["stats"].get("KnowledgeGraph", {})
            kgm = entry["stats"].get("KnowledgeGraphMem", {})
            sh = entry["stats"].get("SheafDatabase", {})
            rows.append(
                f"{label} & ${n:,}$ & ${_mean_ci(kg)}$ & ${_mean_ci(kgm)}$ & ${_mean_ci(sh)}$"
                f" & ${_ratio(kg.get('mean', 0.0), sh.get('mean', 0.0))}$"
                f" & ${_ratio(kgm.get('mean', 0.0), sh.get('mean', 0.0))}$ \\\\"
            )
        rows.append("\\midrule")
    if rows and rows[-1] == "\\midrule":
        rows.pop()
    body = "\n".join(rows)
    return f"""% Auto-generated by scripts/generate_tables.py from results/paper_suite_summary.json
% Do not edit by hand.
\\begin{{table}}[htbp]
\\centering
\\caption{{Query latency in ms by class and scale (mean over ten runs
$\\pm$ 95\\% CI half-width). Lower is better. KG-mem is the
storage-layer control: identical reification and query logic to KG with
dict indexes in place of SQLite. Ratios are SFDB\\,/\\,KG and
SFDB\\,/\\,KG-mem; below $1$ means SFDB is faster.}}
\\label{{tab:query}}
\\small
\\begin{{tabular}}{{llrrrrr}}
\\toprule
Class & Facts & KG (ms) & KG-mem (ms) & SFDB (ms) & vs KG & vs KG-mem \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""


def generate_memory_table(summary: dict) -> str:
    # Below this floor a delta is measurement noise, not signal -- the
    # same 10 MB threshold generate_summary_macros() uses to decide which
    # scales feed \rangememkg{}/\rangememkgmem{} (see that function's
    # comment for why 1 MB was not conservative enough). Cells computed
    # from a sub-floor delta are marked with a dagger rather than
    # silently printed as if they were as trustworthy as the rest of the
    # row.
    floor = 1e7
    rows = []
    mem = summary.get("insert_memory_bytes", {})
    for n_str in sorted(mem, key=int):
        n = int(n_str)
        kg_raw = mem[n_str].get("KnowledgeGraph", 0.0)
        kgm_raw = mem[n_str].get("KnowledgeGraphMem", 0.0)
        sh_raw = mem[n_str].get("SheafDatabase", 0.0)
        kg_mb, kgm_mb, sh_mb = kg_raw / 1e6, kgm_raw / 1e6, sh_raw / 1e6
        if kg_mb:
            kg_dagger = "" if kg_raw >= floor and sh_raw >= floor else "^\\dagger"
            ratio_kg = f"{sh_mb / kg_mb:.2f}\\times{kg_dagger}"
        else:
            ratio_kg = "n/a"
        if kgm_mb:
            kgm_dagger = "" if kgm_raw >= floor and sh_raw >= floor else "^\\dagger"
            ratio_kgm = f"{sh_mb / kgm_mb:.2f}\\times{kgm_dagger}"
        else:
            ratio_kgm = "n/a"
        rows.append(
            f"${n:,}$ & ${kg_mb:.1f}$ & ${kgm_mb:.1f}$ & ${sh_mb:.1f}$"
            f" & ${ratio_kg}$ & ${ratio_kgm}$ \\\\"
        )
    body = "\n".join(rows)
    return f"""% Auto-generated by scripts/generate_tables.py from results/paper_suite_summary.json
% Do not edit by hand.
\\begin{{table}}[htbp]
\\centering
\\caption{{Resident memory delta from inserting $N$ facts (mean over ten
runs). Ratios are SFDB\\,/\\,KG and SFDB\\,/\\,KG-mem. A dagger ($\\dagger$)
marks a ratio computed from at least one delta below the $10$\\,MB
measurement floor; these are noise, not signal (repeated measurement
showed them landing on either side of parity across independent runs),
and are excluded from
the ranges reported in the text.}}
\\label{{tab:memory}}
\\begin{{tabular}}{{lrrrrr}}
\\toprule
Facts & KG (MB) & KG-mem (MB) & SFDB (MB) & vs KG & vs KG-mem \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""


def _fmt_ratio_value(r: float) -> str:
    if r >= 10:
        return f"{r:.0f}"
    if r >= 3:
        return f"{r:.1f}"
    return f"{r:.2f}"


def _fmt_ratio_range(values: list[float]) -> str:
    """Render a min--max speedup range like ``$23$--$32\\times$``."""
    lo, hi = min(values), max(values)
    lo_s, hi_s = _fmt_ratio_value(lo), _fmt_ratio_value(hi)
    if lo_s == hi_s:
        return f"${lo_s}\\times$"
    return f"${lo_s}$--${hi_s}\\times$"


def generate_summary_macros(summary: dict) -> str:
    """Emit headline-range macros so prose numbers regenerate with the run.

    Every macro is a speedup range (baseline mean / SFDB mean; above 1
    means SFDB is faster) except the memory macros, which are cost
    ranges (SFDB / baseline; above 1 means SFDB uses more memory) over
    the scales where both deltas are reliably measurable (>= 1 MB).
    """
    query_ratios: dict[tuple[str, str], list[float]] = {}
    for n_str in summary["query"]:
        for qclass, entry in summary["query"][n_str].items():
            sh = entry["stats"]["SheafDatabase"]["mean"]
            for base in ("KnowledgeGraph", "KnowledgeGraphMem"):
                b = entry["stats"].get(base, {}).get("mean", 0.0)
                if sh and b:
                    query_ratios.setdefault((qclass, base), []).append(b / sh)

    # The smallest scale (100 facts) is excluded from the range macro: repeat
    # process launches at this scale put the SFDB/KG ratio anywhere from
    # ~0.95x to ~1.17x (straddling parity, direction not repeatable), unlike
    # the 1,000+ scales where the ratio is stable and repeatable across
    # launches. Folding an unstable point into a "range" macro would imply a
    # repeatable signal that isn't there; see the module docstring's sibling
    # discussion for the memory table's analogous floor exclusion.
    insert_ratios = []
    smallest_scale_ratio = None
    smallest_scale = min((int(n) for n in summary["insert"]), default=None)
    for n_str in summary["insert"]:
        kg = summary["insert"][n_str]["KnowledgeGraph"]["mean"]
        sh = summary["insert"][n_str]["SheafDatabase"]["mean"]
        if not sh:
            continue
        ratio = kg / sh
        if int(n_str) == smallest_scale:
            smallest_scale_ratio = ratio
        else:
            insert_ratios.append(ratio)

    # 10 MB, not 1 MB: repeated measurement at 1,000 facts (deltas of a
    # few MB, comfortably above a naive 1 MB floor) showed the SFDB/KG
    # ratio landing anywhere from ~0.82x to ~1.21x across five independent
    # process launches -- noise straddling parity, not a stable signal,
    # despite each individual delta clearing 1 MB. 10 MB sits in the
    # empirical gap between the noisy small scales (well under 3 MB at
    # 1,000 facts) and the unambiguous larger ones (tens to hundreds of
    # MB from 10,000 facts on), where the ratio is consistent in
    # direction and grows monotonically with scale across independent
    # runs, matching the structural argument that memory overhead scales
    # with the number of registered open sets.
    mem_floor = 1e7
    mem = summary.get("insert_memory_bytes", {})
    mem_kg, mem_kgm = [], []
    for n_str in mem:
        kg = mem[n_str].get("KnowledgeGraph", 0.0)
        kgm = mem[n_str].get("KnowledgeGraphMem", 0.0)
        sh = mem[n_str].get("SheafDatabase", 0.0)
        if kg >= mem_floor and sh >= mem_floor:
            mem_kg.append(sh / kg)
        if kgm >= mem_floor and sh >= mem_floor:
            mem_kgm.append(sh / kgm)

    scales = sorted(int(n) for n in summary["query"])
    scales_str = ", ".join(f"${n:,}$".replace(",", "\\,") for n in scales)

    macro_map = {
        "rangelookupkg": ("LOOKUP", "KnowledgeGraph"),
        "rangelookupkgmem": ("LOOKUP", "KnowledgeGraphMem"),
        "rangeglobalkg": ("GLOBAL", "KnowledgeGraph"),
        "rangeglobalkgmem": ("GLOBAL", "KnowledgeGraphMem"),
        "rangecontextkg": ("CONTEXT", "KnowledgeGraph"),
        "rangecontextkgmem": ("CONTEXT", "KnowledgeGraphMem"),
        "rangetemporalkg": ("TEMPORAL", "KnowledgeGraph"),
        "rangetemporalkgmem": ("TEMPORAL", "KnowledgeGraphMem"),
        "rangetemporalunbkg": ("TEMPORAL_UNBOUNDED", "KnowledgeGraph"),
        "rangetemporalunbkgmem": ("TEMPORAL_UNBOUNDED", "KnowledgeGraphMem"),
    }
    lines = [
        "% Auto-generated by scripts/generate_tables.py from results/paper_suite_summary.json",
        "% Do not edit by hand. Speedup macros are baseline/SFDB mean ratios",
        "% (above 1 = SFDB faster); memory macros are SFDB/baseline cost ratios.",
    ]
    for name, key in macro_map.items():
        values = query_ratios.get(key)
        rng = _fmt_ratio_range(values) if values else "(unknown)"
        lines.append(f"\\providecommand{{\\{name}}}{{{rng}}}")
    insert_rng = _fmt_ratio_range(insert_ratios) if insert_ratios else "(unknown)"
    smallest_scale_str = (
        _fmt_single_ratio(smallest_scale_ratio) if smallest_scale_ratio else "(unknown)"
    )
    mem_kg_rng = _fmt_ratio_range(mem_kg) if mem_kg else "(unknown)"
    mem_kgm_rng = _fmt_ratio_range(mem_kgm) if mem_kgm else "(unknown)"
    lines.append(f"\\providecommand{{\\rangeinsertkg}}{{{insert_rng}}}")
    lines.append(f"\\providecommand{{\\insertkgsmallestscale}}{{{smallest_scale_str}}}")
    lines.append(f"\\providecommand{{\\rangememkg}}{{{mem_kg_rng}}}")
    lines.append(f"\\providecommand{{\\rangememkgmem}}{{{mem_kgm_rng}}}")
    lines.append(f"\\providecommand{{\\benchscales}}{{{scales_str}}}")
    lines.append(f"\\providecommand{{\\benchscalecount}}{{{len(scales)}}}")
    return "\n".join(lines) + "\n"


def generate_verification_table(summary: dict) -> str:
    """Count 3-way (KG/KG-mem/SFDB) cross-engine verification instances.

    Spans every in-house benchmark that runs the same canonical-form
    equivalence check (Theorem 1's empirical corroboration), not only
    the synthetic suite: the synthetic suite itself
    (results/paper_suite_summary.json), the LUBM standard-benchmark run
    against the in-house engines (results/lubm_benchmark.json), and the
    Wikidata case study (results/wikidata_case_study.json). The
    external-store comparisons (Jena/Virtuoso/GraphDB) are excluded
    deliberately: those check result-count agreement against a single
    external system, not the stronger canonical-form equivalence the
    three in-house engines are held to.
    """
    total = 0
    passed = 0
    for _n_str, classes in summary["query"].items():
        for _qclass, entry in classes.items():
            total += 1
            if entry["verified"]:
                passed += 1

    lubm_path = REPO_ROOT / "results" / "lubm_benchmark.json"
    if lubm_path.exists():
        lubm_data = json.loads(lubm_path.read_text())
        for scale in lubm_data.get("scales", {}).values():
            for entry in scale.get("query", {}).values():
                total += 1
                if entry["verified"]:
                    passed += 1

    wikidata_path = REPO_ROOT / "results" / "wikidata_case_study.json"
    if wikidata_path.exists():
        wikidata_data = json.loads(wikidata_path.read_text())
        for entry in wikidata_data.get("query", {}).values():
            total += 1
            if entry["verified"]:
                passed += 1

    return f"""% Auto-generated by scripts/generate_tables.py from
% results/paper_suite_summary.json, results/lubm_benchmark.json, and
% results/wikidata_case_study.json. Do not edit by hand.
\\providecommand{{\\verifiedcount}}{{{passed}}}
\\providecommand{{\\verifiedtotal}}{{{total}}}
"""


def generate_rdflib_table() -> str | None:
    """Generate the external rdflib reference-point table, if results exist."""
    path = REPO_ROOT / "results" / "rdflib_reference.json"
    if not path.exists():
        return None
    data = json.loads(path.read_text())
    rows = []
    classes = ("LOOKUP", "GLOBAL", "CONTEXT", "TEMPORAL", "TEMPORAL_UNBOUNDED")
    for qclass in classes:
        label = QUERY_CLASS_LABELS[qclass]
        for n_str in sorted(data.get("scales", {}), key=int):
            entry = data["scales"][n_str].get(qclass)
            if entry is None:
                continue
            n = int(n_str)
            rdf_mean = entry["rdflib_mean_ms"]
            sfdb_mean = entry["sfdb_mean_ms"]
            match = "\\checkmark" if entry["counts_match"] else "$\\neq$"
            rows.append(
                f"{label} & ${n:,}$ & ${_fmt(rdf_mean)}$ & ${_fmt(sfdb_mean)}$"
                f" & ${_ratio(rdf_mean, sfdb_mean)}$ & {match} \\\\"
            )
        rows.append("\\midrule")
    if rows and rows[-1] == "\\midrule":
        rows.pop()
    body = "\n".join(rows)
    return f"""% Auto-generated by scripts/generate_tables.py from results/rdflib_reference.json
% Do not edit by hand.
\\begin{{table}}[htbp]
\\centering
\\caption{{External reference point: rdflib (a real, independent,
pure-Python in-memory RDF library queried via SPARQL) versus SFDB on
the same fact streams (mean over ten runs). The ratio is
SFDB\\,/\\,rdflib; below $1$ means SFDB is faster. The last column
records whether both systems returned the same number of results.
rdflib is not a disk-backed production triple store; see the text for
scope.}}
\\label{{tab:rdflib}}
\\small
\\begin{{tabular}}{{llrrrc}}
\\toprule
Class & Facts & rdflib (ms) & SFDB (ms) & Ratio & Counts \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""


def generate_jena_table() -> str | None:
    """Generate the real Apache Jena TDB2 reference-point table, if results exist."""
    path = REPO_ROOT / "results" / "jena_reference.json"
    if not path.exists():
        return None
    data = json.loads(path.read_text())
    rows = []
    classes = ("LOOKUP", "GLOBAL", "CONTEXT", "TEMPORAL", "TEMPORAL_UNBOUNDED")
    for qclass in classes:
        label = QUERY_CLASS_LABELS[qclass]
        for n_str in sorted(data.get("scales", {}), key=int):
            entry = data["scales"][n_str].get(qclass)
            if entry is None:
                continue
            n = int(n_str)
            jena_mean = entry["jena_mean_ms"]
            sfdb_mean = entry["sfdb_mean_ms"]
            match = "\\checkmark" if entry["counts_match"] else "$\\neq$"
            rows.append(
                f"{label} & ${n:,}$ & ${_fmt(jena_mean)}$ & ${_fmt(sfdb_mean)}$"
                f" & ${_ratio(jena_mean, sfdb_mean)}$ & {match} \\\\"
            )
        rows.append("\\midrule")
    if rows and rows[-1] == "\\midrule":
        rows.pop()
    body = "\n".join(rows)
    return f"""% Auto-generated by scripts/generate_tables.py from results/jena_reference.json
% Do not edit by hand.
\\begin{{table}}[htbp]
\\centering
\\caption{{External reference point: a real, disk-backed Apache Jena TDB2
store (via Fuseki, queried over HTTP SPARQL) versus SFDB on the same
fact streams (mean over ten runs). The ratio is SFDB\\,/\\,Jena; below
$1$ means SFDB is faster. The last column
records whether both systems returned the same number of results. Jena
latencies include HTTP round-trip overhead SFDB's in-process calls do
not pay; see the text for how this cuts against SFDB and cannot explain
the crossover on TEMPORAL.}}
\\label{{tab:jena}}
\\small
\\begin{{tabular}}{{llrrrc}}
\\toprule
Class & Facts & Jena TDB2 (ms) & SFDB (ms) & Ratio & Counts \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""


def _fmt_single_ratio(r: float) -> str:
    return f"${_fmt_ratio_value(r)}\\times$"


def generate_jena_macros() -> str:
    """Speedup macros for the Jena TDB2 comparison, if results exist.

    Emits both an all-scales range (dominated by the smallest scale,
    where Jena's fixed HTTP overhead versus SFDB's sub-millisecond
    in-process calls swamps any architectural signal) and a
    largest-scale-only point estimate (the scale at which the
    LOOKUP/GLOBAL-vs-CONTEXT/TEMPORAL crossover the paper discusses is
    actually visible), so prose citing the crossover at $10^5$ facts
    does not have to hand-transcribe a number out of the range.
    """
    path = REPO_ROOT / "results" / "jena_reference.json"
    if not path.exists():
        return (
            "% results/jena_reference.json not found; Jena macros left as (unknown).\n"
            "\\providecommand{\\jenaavailable}{false}\n"
        )
    data = json.loads(path.read_text())
    classes = ("LOOKUP", "GLOBAL", "CONTEXT", "TEMPORAL", "TEMPORAL_UNBOUNDED")
    macro_names = {
        "LOOKUP": "rangelookupjena",
        "GLOBAL": "rangeglobaljena",
        "CONTEXT": "rangecontextjena",
        "TEMPORAL": "rangetemporaljena",
        "TEMPORAL_UNBOUNDED": "rangetemporalunbjena",
    }
    large_macro_names = {
        "LOOKUP": "lookupjenalarge",
        "GLOBAL": "globaljenalarge",
        "CONTEXT": "contextjenalarge",
        "TEMPORAL": "temporaljenalarge",
        "TEMPORAL_UNBOUNDED": "temporalunbjenalarge",
    }
    all_scales = data.get("scales", {})
    scales = sorted((int(n) for n in all_scales), reverse=True)
    largest_scale_str = str(scales[0]) if scales else None
    largest_scale = all_scales.get(largest_scale_str, {}) if largest_scale_str else {}
    lines = [
        "% Auto-generated by scripts/generate_tables.py from results/jena_reference.json",
        "% Do not edit by hand. Ratios are jena_mean/sfdb_mean (above 1 = SFDB faster).",
        "% The *large macros are single-scale point estimates at the largest",
        "% scale measured, not ranges -- see the module docstring above.",
        "\\providecommand{\\jenaavailable}{true}",
        f"\\providecommand{{\\jenalargescale}}{{${largest_scale_str}$}}"
        if largest_scale_str
        else "\\providecommand{\\jenalargescale}{(unknown)}",
    ]
    for qclass in classes:
        ratios = []
        for entry in all_scales.values():
            e = entry.get(qclass)
            if e and e.get("sfdb_mean_ms"):
                ratios.append(e["jena_mean_ms"] / e["sfdb_mean_ms"])
        rng = _fmt_ratio_range(ratios) if ratios else "(unknown)"
        lines.append(f"\\providecommand{{\\{macro_names[qclass]}}}{{{rng}}}")

        large_entry = largest_scale.get(qclass)
        if large_entry and large_entry.get("sfdb_mean_ms"):
            large_ratio = large_entry["jena_mean_ms"] / large_entry["sfdb_mean_ms"]
            large_str = _fmt_single_ratio(large_ratio)
        else:
            large_str = "(unknown)"
        lines.append(f"\\providecommand{{\\{large_macro_names[qclass]}}}{{{large_str}}}")
    return "\n".join(lines) + "\n"


def generate_virtuoso_table() -> str | None:
    """Generate the real OpenLink Virtuoso reference-point table, if results exist."""
    path = REPO_ROOT / "results" / "virtuoso_reference.json"
    if not path.exists():
        return None
    data = json.loads(path.read_text())
    rows = []
    classes = ("LOOKUP", "GLOBAL", "CONTEXT", "TEMPORAL", "TEMPORAL_UNBOUNDED")
    for qclass in classes:
        label = QUERY_CLASS_LABELS[qclass]
        for n_str in sorted(data.get("scales", {}), key=int):
            entry = data["scales"][n_str].get(qclass)
            if entry is None:
                continue
            n = int(n_str)
            virtuoso_mean = entry["virtuoso_mean_ms"]
            sfdb_mean = entry["sfdb_mean_ms"]
            match = "\\checkmark" if entry["counts_match"] else "$\\neq$"
            rows.append(
                f"{label} & ${n:,}$ & ${_fmt(virtuoso_mean)}$ & ${_fmt(sfdb_mean)}$"
                f" & ${_ratio(virtuoso_mean, sfdb_mean)}$ & {match} \\\\"
            )
        rows.append("\\midrule")
    if rows and rows[-1] == "\\midrule":
        rows.pop()
    body = "\n".join(rows)
    return f"""% Auto-generated by scripts/generate_tables.py from results/virtuoso_reference.json
% Do not edit by hand.
\\begin{{table}}[htbp]
\\centering
\\caption{{External reference point: a real, disk-backed OpenLink
Virtuoso store (open-source edition, queried over HTTP SPARQL) versus
SFDB on the same fact streams (mean over ten runs). The ratio is
SFDB\\,/\\,Virtuoso; below $1$ means SFDB is faster. The last column
records whether both systems returned the same number of results.
Virtuoso latencies include HTTP round-trip and Digest-authentication
overhead SFDB's in-process calls do not pay; see the text for how this
cuts against SFDB and cannot explain the crossover on
TEMPORAL.}}
\\label{{tab:virtuoso}}
\\small
\\begin{{tabular}}{{llrrrc}}
\\toprule
Class & Facts & Virtuoso (ms) & SFDB (ms) & Ratio & Counts \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""


def generate_virtuoso_macros() -> str:
    """Speedup macros for the Virtuoso comparison, if results exist.

    Mirrors generate_jena_macros(): an all-scales range plus a
    largest-scale-only point estimate, so prose citing the crossover at
    $10^5$ facts does not have to hand-transcribe a number out of a
    range dominated by small-scale HTTP overhead.
    """
    path = REPO_ROOT / "results" / "virtuoso_reference.json"
    if not path.exists():
        return (
            "% results/virtuoso_reference.json not found; Virtuoso macros left as (unknown).\n"
            "\\providecommand{\\virtuosoavailable}{false}\n"
        )
    data = json.loads(path.read_text())
    classes = ("LOOKUP", "GLOBAL", "CONTEXT", "TEMPORAL", "TEMPORAL_UNBOUNDED")
    macro_names = {
        "LOOKUP": "rangelookupvirtuoso",
        "GLOBAL": "rangeglobalvirtuoso",
        "CONTEXT": "rangecontextvirtuoso",
        "TEMPORAL": "rangetemporalvirtuoso",
        "TEMPORAL_UNBOUNDED": "rangetemporalunbvirtuoso",
    }
    large_macro_names = {
        "LOOKUP": "lookupvirtuosolarge",
        "GLOBAL": "globalvirtuosolarge",
        "CONTEXT": "contextvirtuosolarge",
        "TEMPORAL": "temporalvirtuosolarge",
        "TEMPORAL_UNBOUNDED": "temporalunbvirtuosolarge",
    }
    all_scales = data.get("scales", {})
    scales = sorted((int(n) for n in all_scales), reverse=True)
    largest_scale_str = str(scales[0]) if scales else None
    largest_scale = all_scales.get(largest_scale_str, {}) if largest_scale_str else {}
    lines = [
        "% Auto-generated by scripts/generate_tables.py from results/virtuoso_reference.json",
        "% Do not edit by hand. Ratios are virtuoso_mean/sfdb_mean (above 1 = SFDB faster).",
        "% The *large macros are single-scale point estimates at the largest",
        "% scale measured, not ranges -- see the module docstring above.",
        "\\providecommand{\\virtuosoavailable}{true}",
        f"\\providecommand{{\\virtuosolargescale}}{{${largest_scale_str}$}}"
        if largest_scale_str
        else "\\providecommand{\\virtuosolargescale}{(unknown)}",
    ]
    for qclass in classes:
        ratios = []
        for entry in all_scales.values():
            e = entry.get(qclass)
            if e and e.get("sfdb_mean_ms"):
                ratios.append(e["virtuoso_mean_ms"] / e["sfdb_mean_ms"])
        rng = _fmt_ratio_range(ratios) if ratios else "(unknown)"
        lines.append(f"\\providecommand{{\\{macro_names[qclass]}}}{{{rng}}}")

        large_entry = largest_scale.get(qclass)
        if large_entry and large_entry.get("sfdb_mean_ms"):
            large_ratio = large_entry["virtuoso_mean_ms"] / large_entry["sfdb_mean_ms"]
            large_str = _fmt_single_ratio(large_ratio)
        else:
            large_str = "(unknown)"
        lines.append(f"\\providecommand{{\\{large_macro_names[qclass]}}}{{{large_str}}}")
    return "\n".join(lines) + "\n"


def generate_graphdb_table() -> str | None:
    """Generate the real Ontotext GraphDB reference-point table, if results exist."""
    path = REPO_ROOT / "results" / "graphdb_reference.json"
    if not path.exists():
        return None
    data = json.loads(path.read_text())
    rows = []
    classes = ("LOOKUP", "GLOBAL", "CONTEXT", "TEMPORAL", "TEMPORAL_UNBOUNDED")
    for qclass in classes:
        label = QUERY_CLASS_LABELS[qclass]
        for n_str in sorted(data.get("scales", {}), key=int):
            entry = data["scales"][n_str].get(qclass)
            if entry is None:
                continue
            n = int(n_str)
            graphdb_mean = entry["graphdb_mean_ms"]
            sfdb_mean = entry["sfdb_mean_ms"]
            match = "\\checkmark" if entry["counts_match"] else "$\\neq$"
            rows.append(
                f"{label} & ${n:,}$ & ${_fmt(graphdb_mean)}$ & ${_fmt(sfdb_mean)}$"
                f" & ${_ratio(graphdb_mean, sfdb_mean)}$ & {match} \\\\"
            )
        rows.append("\\midrule")
    if rows and rows[-1] == "\\midrule":
        rows.pop()
    body = "\n".join(rows)
    return f"""% Auto-generated by scripts/generate_tables.py from results/graphdb_reference.json
% Do not edit by hand.
\\begin{{table}}[htbp]
\\centering
\\caption{{External reference point: a real, disk-backed Ontotext
GraphDB store (free edition, queried over HTTP SPARQL) versus SFDB on
the same fact streams (mean over ten runs). The ratio is
SFDB\\,/\\,GraphDB; below $1$ means SFDB is faster. The last column
records whether both systems returned the same number of results.
GraphDB latencies include an HTTP round trip SFDB's in-process calls do
not pay; see the text for how this cuts against SFDB and cannot explain
the crossover on TEMPORAL.}}
\\label{{tab:graphdb}}
\\small
\\begin{{tabular}}{{llrrrc}}
\\toprule
Class & Facts & GraphDB (ms) & SFDB (ms) & Ratio & Counts \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""


def generate_graphdb_macros() -> str:
    """Speedup macros for the GraphDB comparison, if results exist.

    Mirrors generate_jena_macros()/generate_virtuoso_macros(): an
    all-scales range plus a largest-scale-only point estimate, so prose
    citing the crossover at $10^5$ facts does not have to hand-transcribe
    a number out of a range dominated by small-scale HTTP overhead.
    """
    path = REPO_ROOT / "results" / "graphdb_reference.json"
    if not path.exists():
        return (
            "% results/graphdb_reference.json not found; GraphDB macros left as (unknown).\n"
            "\\providecommand{\\graphdbavailable}{false}\n"
        )
    data = json.loads(path.read_text())
    classes = ("LOOKUP", "GLOBAL", "CONTEXT", "TEMPORAL", "TEMPORAL_UNBOUNDED")
    macro_names = {
        "LOOKUP": "rangelookupgraphdb",
        "GLOBAL": "rangeglobalgraphdb",
        "CONTEXT": "rangecontextgraphdb",
        "TEMPORAL": "rangetemporalgraphdb",
        "TEMPORAL_UNBOUNDED": "rangetemporalunbgraphdb",
    }
    large_macro_names = {
        "LOOKUP": "lookupgraphdblarge",
        "GLOBAL": "globalgraphdblarge",
        "CONTEXT": "contextgraphdblarge",
        "TEMPORAL": "temporalgraphdblarge",
        "TEMPORAL_UNBOUNDED": "temporalunbgraphdblarge",
    }
    all_scales = data.get("scales", {})
    scales = sorted((int(n) for n in all_scales), reverse=True)
    largest_scale_str = str(scales[0]) if scales else None
    largest_scale = all_scales.get(largest_scale_str, {}) if largest_scale_str else {}
    lines = [
        "% Auto-generated by scripts/generate_tables.py from results/graphdb_reference.json",
        "% Do not edit by hand. Ratios are graphdb_mean/sfdb_mean (above 1 = SFDB faster).",
        "% The *large macros are single-scale point estimates at the largest",
        "% scale measured, not ranges -- see the module docstring above.",
        "\\providecommand{\\graphdbavailable}{true}",
        f"\\providecommand{{\\graphdblargescale}}{{${largest_scale_str}$}}"
        if largest_scale_str
        else "\\providecommand{\\graphdblargescale}{(unknown)}",
    ]
    for qclass in classes:
        ratios = []
        for entry in all_scales.values():
            e = entry.get(qclass)
            if e and e.get("sfdb_mean_ms"):
                ratios.append(e["graphdb_mean_ms"] / e["sfdb_mean_ms"])
        rng = _fmt_ratio_range(ratios) if ratios else "(unknown)"
        lines.append(f"\\providecommand{{\\{macro_names[qclass]}}}{{{rng}}}")

        large_entry = largest_scale.get(qclass)
        if large_entry and large_entry.get("sfdb_mean_ms"):
            large_ratio = large_entry["graphdb_mean_ms"] / large_entry["sfdb_mean_ms"]
            large_str = _fmt_single_ratio(large_ratio)
        else:
            large_str = "(unknown)"
        lines.append(f"\\providecommand{{\\{large_macro_names[qclass]}}}{{{large_str}}}")
    return "\n".join(lines) + "\n"


def generate_lubm_table() -> str | None:
    """Standard-benchmark-workload table (LUBM), if results exist."""
    path = REPO_ROOT / "results" / "lubm_benchmark.json"
    if not path.exists():
        return None
    data = json.loads(path.read_text())
    rows = []
    classes = ("LOOKUP", "GLOBAL", "CONTEXT", "TEMPORAL", "TEMPORAL_UNBOUNDED")
    for qclass in classes:
        label = QUERY_CLASS_LABELS[qclass]
        for n_str in sorted(data.get("scales", {}), key=int):
            entry = data["scales"][n_str]["query"].get(qclass)
            if entry is None:
                continue
            n = int(n_str)
            kg = entry["stats"]["KnowledgeGraph"]["mean"]
            kgm = entry["stats"]["KnowledgeGraphMem"]["mean"]
            sh = entry["stats"]["SheafDatabase"]["mean"]
            match = "\\checkmark" if entry.get("verified") else "$\\neq$"
            rows.append(
                f"{label} & ${n:,}$ & ${_fmt(kg)}$ & ${_fmt(kgm)}$ & ${_fmt(sh)}$"
                f" & ${_ratio(kg, sh)}$ & ${_ratio(kgm, sh)}$ & {match} \\\\"
            )
        rows.append("\\midrule")
    if rows and rows[-1] == "\\midrule":
        rows.pop()
    body = "\n".join(rows)
    return f"""% Auto-generated by scripts/generate_tables.py from results/lubm_benchmark.json
% Do not edit by hand.
\\begin{{table}}[htbp]
\\centering
\\caption{{Standard benchmark workload: LUBM (Lehigh University
Benchmark) data instead of this project's synthetic generator, scaled
by university count (\\texttt{{scripts/lubm\\_benchmark.py}}) to land
close to this paper's usual four fact-count scales. Latency in ms
(mean over ten runs). Ratios are SFDB\\,/\\,KG and SFDB\\,/\\,KG-mem;
below $1$ means SFDB is faster. The last column records three-way
cross-engine result-count agreement.}}
\\label{{tab:lubm}}
\\footnotesize
\\resizebox{{\\textwidth}}{{!}}{{%
\\begin{{tabular}}{{llrrrrrc}}
\\toprule
Class & Facts & KG (ms) & KG-mem (ms) & SFDB (ms) & vs KG & vs KG-mem & Counts \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}%
}}
\\end{{table}}
"""


def generate_lubm_macros() -> str:
    """Speedup macros for the LUBM standard-workload comparison, if results exist."""
    path = REPO_ROOT / "results" / "lubm_benchmark.json"
    if not path.exists():
        return (
            "% results/lubm_benchmark.json not found; LUBM macros left as (unknown).\n"
            "\\providecommand{\\lubmavailable}{false}\n"
        )
    data = json.loads(path.read_text())
    classes = ("LOOKUP", "GLOBAL", "CONTEXT", "TEMPORAL", "TEMPORAL_UNBOUNDED")
    macro_names = {
        "LOOKUP": ("rangelookuplubmkg", "rangelookuplubmkgmem"),
        "GLOBAL": ("rangegloballubmkg", "rangegloballubmkgmem"),
        "CONTEXT": ("rangecontextlubmkg", "rangecontextlubmkgmem"),
        "TEMPORAL": ("rangetemporallubmkg", "rangetemporallubmkgmem"),
        "TEMPORAL_UNBOUNDED": ("rangetemporalunblubmkg", "rangetemporalunblubmkgmem"),
    }
    large_macro_names = {
        "LOOKUP": ("lookuplubmkglarge", "lookuplubmkgmemlarge"),
        "GLOBAL": ("globallubmkglarge", "globallubmkgmemlarge"),
        "CONTEXT": ("contextlubmkglarge", "contextlubmkgmemlarge"),
        "TEMPORAL": ("temporallubmkglarge", "temporallubmkgmemlarge"),
        "TEMPORAL_UNBOUNDED": ("temporalunblubmkglarge", "temporalunblubmkgmemlarge"),
    }
    all_scales = data.get("scales", {})
    scales = sorted((int(n) for n in all_scales), reverse=True)
    largest_scale_str = str(scales[0]) if scales else None
    largest_scale_entry = all_scales.get(largest_scale_str, {}) if largest_scale_str else {}
    largest_scale = largest_scale_entry.get("query", {})
    lines = [
        "% Auto-generated by scripts/generate_tables.py from results/lubm_benchmark.json",
        "% Do not edit by hand. Ratios are engine_mean/sfdb_mean (above 1 = SFDB faster).",
        "\\providecommand{\\lubmavailable}{true}",
        f"\\providecommand{{\\lubmlargescale}}{{${int(largest_scale_str):,}$}}"
        if largest_scale_str
        else "\\providecommand{\\lubmlargescale}{(unknown)}",
        f"\\providecommand{{\\lubmnumfacts}}{{${int(largest_scale_str):,}$}}"
        if largest_scale_str
        else "\\providecommand{\\lubmnumfacts}{(unknown)}",
    ]
    for qclass in classes:
        kg_macro, kgm_macro = macro_names[qclass]
        kg_ratios, kgm_ratios = [], []
        for entry in all_scales.values():
            e = entry.get("query", {}).get(qclass)
            if e and e["stats"]["SheafDatabase"]["mean"]:
                sh = e["stats"]["SheafDatabase"]["mean"]
                kg_ratios.append(e["stats"]["KnowledgeGraph"]["mean"] / sh)
                kgm_ratios.append(e["stats"]["KnowledgeGraphMem"]["mean"] / sh)
        kg_rng = _fmt_ratio_range(kg_ratios) if kg_ratios else "(unknown)"
        kgm_rng = _fmt_ratio_range(kgm_ratios) if kgm_ratios else "(unknown)"
        lines.append(f"\\providecommand{{\\{kg_macro}}}{{{kg_rng}}}")
        lines.append(f"\\providecommand{{\\{kgm_macro}}}{{{kgm_rng}}}")

        large_kg_macro, large_kgm_macro = large_macro_names[qclass]
        large_entry = largest_scale.get(qclass)
        if large_entry and large_entry["stats"]["SheafDatabase"]["mean"]:
            sh = large_entry["stats"]["SheafDatabase"]["mean"]
            large_kg_str = _fmt_single_ratio(large_entry["stats"]["KnowledgeGraph"]["mean"] / sh)
            large_kgm_str = _fmt_single_ratio(
                large_entry["stats"]["KnowledgeGraphMem"]["mean"] / sh
            )
        else:
            large_kg_str = "(unknown)"
            large_kgm_str = "(unknown)"
        lines.append(f"\\providecommand{{\\{large_kg_macro}}}{{{large_kg_str}}}")
        lines.append(f"\\providecommand{{\\{large_kgm_macro}}}{{{large_kgm_str}}}")
    return "\n".join(lines) + "\n"


# Store label as it appears in prose/table headers, and the macro-name
# fragment (must be a valid (La)TeX command-name substring: letters only).
LUBM_EXTERNAL_STORES: dict[str, tuple[str, str]] = {
    "jena": ("Jena TDB2", "lubmjena"),
    "virtuoso": ("Virtuoso", "lubmvirtuoso"),
    "graphdb": ("GraphDB", "lubmgraphdb"),
}


def generate_lubm_external_table(store: str) -> str | None:
    """LUBM-vs-<external store> table, if results exist.

    Varies both axes at once (organic-shaped dataset, external engine)
    relative to scripts/lubm_benchmark.py (LUBM vs. in-house engines
    only) and scripts/{jena,virtuoso,graphdb}_reference.py (synthetic
    generator vs. external engine only).
    """
    label, _ = LUBM_EXTERNAL_STORES[store]
    path = REPO_ROOT / "results" / f"lubm_{store}_reference.json"
    if not path.exists():
        return None
    data = json.loads(path.read_text())
    rows = []
    classes = ("LOOKUP", "GLOBAL", "CONTEXT", "TEMPORAL", "TEMPORAL_UNBOUNDED")
    for qclass in classes:
        qlabel = QUERY_CLASS_LABELS[qclass]
        for n_str in sorted(data.get("scales", {}), key=int):
            entry = data["scales"][n_str].get(qclass)
            if entry is None:
                continue
            n = int(n_str)
            ext_mean = entry["external_mean_ms"]
            sfdb_mean = entry["sfdb_mean_ms"]
            match = "\\checkmark" if entry["counts_match"] else "$\\neq$"
            rows.append(
                f"{qlabel} & ${n:,}$ & ${_fmt(ext_mean)}$ & ${_fmt(sfdb_mean)}$"
                f" & ${_ratio(ext_mean, sfdb_mean)}$ & {match} \\\\"
            )
        rows.append("\\midrule")
    if rows and rows[-1] == "\\midrule":
        rows.pop()
    body = "\n".join(rows)
    return f"""% Auto-generated by scripts/generate_tables.py
% from results/lubm_{store}_reference.json. Do not edit by hand.
\\begin{{table}}[htbp]
\\centering
\\caption{{LUBM data against a real, disk-backed {label} store ---
varying both the dataset (LUBM rather than this project's synthetic
generator) and the comparison engine (a real production store rather
than the in-house KG/KG-mem baselines) at once. The ratio is
SFDB\\,/\\,{label}; below $1$ means SFDB is faster. The last column
records whether both systems returned the same number of results.}}
\\label{{tab:lubm-{store}}}
\\small
\\begin{{tabular}}{{llrrrc}}
\\toprule
Class & Facts & {label} (ms) & SFDB (ms) & Ratio & Counts \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""


def generate_lubm_external_macros(store: str) -> str:
    """Speedup macros for the LUBM-vs-<external store> comparison, if results exist."""
    _, macro_prefix = LUBM_EXTERNAL_STORES[store]
    path = REPO_ROOT / "results" / f"lubm_{store}_reference.json"
    if not path.exists():
        return (
            f"% results/lubm_{store}_reference.json not found; macros left as (unknown).\n"
            f"\\providecommand{{\\{macro_prefix}available}}{{false}}\n"
        )
    data = json.loads(path.read_text())
    classes = ("LOOKUP", "GLOBAL", "CONTEXT", "TEMPORAL", "TEMPORAL_UNBOUNDED")
    class_suffix = {
        "LOOKUP": "lookup",
        "GLOBAL": "global",
        "CONTEXT": "context",
        "TEMPORAL": "temporal",
        "TEMPORAL_UNBOUNDED": "temporalunb",
    }
    all_scales = data.get("scales", {})
    scales = sorted((int(n) for n in all_scales), reverse=True)
    largest_scale_str = str(scales[0]) if scales else None
    largest_scale = all_scales.get(largest_scale_str, {}) if largest_scale_str else {}
    lines = [
        f"% Auto-generated by scripts/generate_tables.py from results/lubm_{store}_reference.json",
        "% Do not edit by hand. Ratios are external_mean/sfdb_mean (above 1 = SFDB faster).",
        f"\\providecommand{{\\{macro_prefix}available}}{{true}}",
        f"\\providecommand{{\\{macro_prefix}largescale}}{{${largest_scale_str}$}}"
        if largest_scale_str
        else f"\\providecommand{{\\{macro_prefix}largescale}}{{(unknown)}}",
    ]
    for qclass in classes:
        suffix = class_suffix[qclass]
        ratios = []
        for entry in all_scales.values():
            e = entry.get(qclass)
            if e and e.get("sfdb_mean_ms"):
                ratios.append(e["external_mean_ms"] / e["sfdb_mean_ms"])
        rng = _fmt_ratio_range(ratios) if ratios else "(unknown)"
        lines.append(f"\\providecommand{{\\range{suffix}{macro_prefix}}}{{{rng}}}")

        large_entry = largest_scale.get(qclass)
        if large_entry and large_entry.get("sfdb_mean_ms"):
            large_ratio = large_entry["external_mean_ms"] / large_entry["sfdb_mean_ms"]
            large_str = _fmt_single_ratio(large_ratio)
        else:
            large_str = "(unknown)"
        lines.append(f"\\providecommand{{\\{suffix}{macro_prefix}large}}{{{large_str}}}")
    return "\n".join(lines) + "\n"


def generate_wikidata_case_study_table() -> str | None:
    """Real-world case-study table (Wikidata office-holders), if results exist."""
    path = REPO_ROOT / "results" / "wikidata_case_study.json"
    if not path.exists():
        return None
    data = json.loads(path.read_text())
    rows = []
    ins = data.get("insert", {})
    if ins:
        kg = ins.get("KnowledgeGraph", {})
        kgm = ins.get("KnowledgeGraphMem", {})
        sh = ins.get("SheafDatabase", {})
        rows.append(
            f"Insert & ${_mean_ci(kg)}$ & ${_mean_ci(kgm)}$ & ${_mean_ci(sh)}$"
            f" & ${_ratio(kg.get('mean', 0.0), sh.get('mean', 0.0))}$"
            f" & ${_ratio(kgm.get('mean', 0.0), sh.get('mean', 0.0))}$ & --- \\\\"
        )
        rows.append("\\midrule")
    classes = ("LOOKUP", "GLOBAL", "CONTEXT", "TEMPORAL", "TEMPORAL_UNBOUNDED")
    for qclass in classes:
        entry = data.get("query", {}).get(qclass)
        if entry is None:
            continue
        label = QUERY_CLASS_LABELS[qclass]
        kg = entry["stats"].get("KnowledgeGraph", {})
        kgm = entry["stats"].get("KnowledgeGraphMem", {})
        sh = entry["stats"].get("SheafDatabase", {})
        match = "\\checkmark" if entry.get("verified") else "$\\neq$"
        rows.append(
            f"{label} & ${_mean_ci(kg)}$ & ${_mean_ci(kgm)}$ & ${_mean_ci(sh)}$"
            f" & ${_ratio(kg.get('mean', 0.0), sh.get('mean', 0.0))}$"
            f" & ${_ratio(kgm.get('mean', 0.0), sh.get('mean', 0.0))}$ & {match} \\\\"
        )
    body = "\n".join(rows)
    num_facts = data.get("num_facts", 0)
    return f"""% Auto-generated by scripts/generate_tables.py from results/wikidata_case_study.json
% Do not edit by hand.
\\begin{{table}}[htbp]
\\centering
\\caption{{Real-world case study: {num_facts:,} genuine Wikidata
``position held'' facts (national heads of state and government, with
recorded start/end dates and country), not this project's synthetic
generator. KG, KG-mem, and SFDB columns are latency in ms (mean over
ten runs $\\pm$ 95\\% CI
half-width). Ratios are SFDB\\,/\\,KG and SFDB\\,/\\,KG-mem; below $1$
means SFDB is faster. The last column records three-way cross-engine
result-count agreement (insert has no query result to compare).}}
\\label{{tab:wikidata-case-study}}
\\footnotesize
\\resizebox{{\\textwidth}}{{!}}{{%
\\begin{{tabular}}{{lrrrrrc}}
\\toprule
Class & KG & KG-mem & SFDB & vs KG & vs KG-mem & Counts \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}%
}}
\\end{{table}}
"""


def generate_wikidata_case_study_macros() -> str:
    """Headline macros for the Wikidata case study, if results exist."""
    path = REPO_ROOT / "results" / "wikidata_case_study.json"
    if not path.exists():
        return (
            "% results/wikidata_case_study.json not found; case-study macros "
            "left as (unknown).\n"
            "\\providecommand{\\wikidatacasestudyavailable}{false}\n"
        )
    data = json.loads(path.read_text())
    lines = [
        "% Auto-generated by scripts/generate_tables.py from "
        "results/wikidata_case_study.json",
        "% Do not edit by hand.",
        "\\providecommand{\\wikidatacasestudyavailable}{true}",
        f"\\providecommand{{\\wikidatanumfacts}}{{${data.get('num_facts', 0):,}$}}",
    ]
    macro_names = {
        "LOOKUP": ("wikidatalookupkg", "wikidatalookupkgmem"),
        "GLOBAL": ("wikidataglobalkg", "wikidataglobalkgmem"),
        "CONTEXT": ("wikidatacontextkg", "wikidatacontextkgmem"),
        "TEMPORAL": ("wikidatatemporalkg", "wikidatatemporalkgmem"),
        "TEMPORAL_UNBOUNDED": ("wikidatatemporalunbkg", "wikidatatemporalunbkgmem"),
    }
    for qclass, (kg_macro, kgm_macro) in macro_names.items():
        entry = data.get("query", {}).get(qclass)
        if entry is None:
            lines.append(f"\\providecommand{{\\{kg_macro}}}{{(unknown)}}")
            lines.append(f"\\providecommand{{\\{kgm_macro}}}{{(unknown)}}")
            continue
        kg_mean = entry["stats"].get("KnowledgeGraph", {}).get("mean", 0.0)
        kgm_mean = entry["stats"].get("KnowledgeGraphMem", {}).get("mean", 0.0)
        sh_mean = entry["stats"].get("SheafDatabase", {}).get("mean", 0.0)
        kg_str = _fmt_single_ratio(sh_mean / kg_mean) if kg_mean else "(unknown)"
        kgm_str = _fmt_single_ratio(sh_mean / kgm_mean) if kgm_mean else "(unknown)"
        lines.append(f"\\providecommand{{\\{kg_macro}}}{{{kg_str}}}")
        lines.append(f"\\providecommand{{\\{kgm_macro}}}{{{kgm_str}}}")
    return "\n".join(lines) + "\n"


def generate_reproducibility_macros(repro: dict) -> str:
    memory_gb = repro.get("memory_total", 0) / 1e9
    return f"""% Auto-generated by scripts/generate_tables.py from results/paper_suite_reproducibility.json
% Do not edit by hand.
\\providecommand{{\\generatedcpu}}{{{repro.get("cpu_model", "unknown")} ({repro.get("cpu_count", "?")} cores)}}
\\providecommand{{\\generatedmemory}}{{{memory_gb:.1f} GB}}
\\providecommand{{\\generatedos}}{{{repro.get("os", "unknown")} {repro.get("os_release", "")}}}
\\providecommand{{\\generatedhash}}{{{repro.get("git", {}).get("commit", "unknown")[:7]}}}
\\providecommand{{\\generatedpython}}{{{repro.get("python_version", "unknown")}}}
\\providecommand{{\\generateduvlock}}{{{repro.get("uv_lock", "unknown")}}}
\\providecommand{{\\generatedchecksum}}{{{repro.get("dataset_checksum", "unknown")}}}
\\providecommand{{\\generatedseed}}{{{repro.get("seed", "unknown")}}}
\\providecommand{{\\generateddate}}{{{repro.get("timestamp", "unknown")}}}
"""


def main() -> int:
    if not SUMMARY_PATH.exists():
        print(f"error: {SUMMARY_PATH} not found. Run `uv run sfdb benchmark` first.", file=sys.stderr)
        return 1

    summary = json.loads(SUMMARY_PATH.read_text())
    TABLES_DIR.mkdir(parents=True, exist_ok=True)

    (TABLES_DIR / "insert_latency.tex").write_text(generate_insert_table(summary))
    (TABLES_DIR / "query_latency.tex").write_text(generate_query_table(summary))
    (TABLES_DIR / "memory.tex").write_text(generate_memory_table(summary))
    (TABLES_DIR / "verification_counts.tex").write_text(generate_verification_table(summary))
    (TABLES_DIR / "summary_macros.tex").write_text(generate_summary_macros(summary))

    for name in (
        "insert_latency",
        "query_latency",
        "memory",
        "verification_counts",
        "summary_macros",
    ):
        print(f"Wrote {TABLES_DIR / f'{name}.tex'}")

    rdflib_table = generate_rdflib_table()
    if rdflib_table is not None:
        (TABLES_DIR / "rdflib_reference.tex").write_text(rdflib_table)
        print(f"Wrote {TABLES_DIR / 'rdflib_reference.tex'}")
    else:
        print(
            "note: results/rdflib_reference.json not found; rdflib table not regenerated "
            "(run scripts/rdflib_reference.py).",
        )

    jena_table = generate_jena_table()
    if jena_table is not None:
        (TABLES_DIR / "jena_reference.tex").write_text(jena_table)
        print(f"Wrote {TABLES_DIR / 'jena_reference.tex'}")
    else:
        print(
            "note: results/jena_reference.json not found; Jena table not regenerated "
            "(run scripts/jena_reference.py against a running Fuseki server).",
        )
    (TABLES_DIR / "jena_macros.tex").write_text(generate_jena_macros())
    print(f"Wrote {TABLES_DIR / 'jena_macros.tex'}")

    virtuoso_table = generate_virtuoso_table()
    if virtuoso_table is not None:
        (TABLES_DIR / "virtuoso_reference.tex").write_text(virtuoso_table)
        print(f"Wrote {TABLES_DIR / 'virtuoso_reference.tex'}")
    else:
        print(
            "note: results/virtuoso_reference.json not found; Virtuoso table not regenerated "
            "(run scripts/virtuoso_reference.py against a running Virtuoso instance).",
        )
    (TABLES_DIR / "virtuoso_macros.tex").write_text(generate_virtuoso_macros())
    print(f"Wrote {TABLES_DIR / 'virtuoso_macros.tex'}")

    graphdb_table = generate_graphdb_table()
    if graphdb_table is not None:
        (TABLES_DIR / "graphdb_reference.tex").write_text(graphdb_table)
        print(f"Wrote {TABLES_DIR / 'graphdb_reference.tex'}")
    else:
        print(
            "note: results/graphdb_reference.json not found; GraphDB table not "
            "regenerated (run scripts/graphdb_reference.py against a running GraphDB instance).",
        )
    (TABLES_DIR / "graphdb_macros.tex").write_text(generate_graphdb_macros())
    print(f"Wrote {TABLES_DIR / 'graphdb_macros.tex'}")

    lubm_table = generate_lubm_table()
    if lubm_table is not None:
        (TABLES_DIR / "lubm_benchmark.tex").write_text(lubm_table)
        print(f"Wrote {TABLES_DIR / 'lubm_benchmark.tex'}")
    else:
        print(
            "note: results/lubm_benchmark.json not found; LUBM table not "
            "regenerated (run scripts/lubm_benchmark.py).",
        )
    (TABLES_DIR / "lubm_macros.tex").write_text(generate_lubm_macros())
    print(f"Wrote {TABLES_DIR / 'lubm_macros.tex'}")

    for store in LUBM_EXTERNAL_STORES:
        store_table = generate_lubm_external_table(store)
        if store_table is not None:
            (TABLES_DIR / f"lubm_{store}_reference.tex").write_text(store_table)
            print(f"Wrote {TABLES_DIR / f'lubm_{store}_reference.tex'}")
        else:
            print(
                f"note: results/lubm_{store}_reference.json not found; LUBM-vs-{store} table "
                f"not regenerated (run scripts/lubm_external_reference.py --store {store}).",
            )
        (TABLES_DIR / f"lubm_{store}_macros.tex").write_text(generate_lubm_external_macros(store))
        print(f"Wrote {TABLES_DIR / f'lubm_{store}_macros.tex'}")

    wikidata_table = generate_wikidata_case_study_table()
    if wikidata_table is not None:
        (TABLES_DIR / "wikidata_case_study.tex").write_text(wikidata_table)
        print(f"Wrote {TABLES_DIR / 'wikidata_case_study.tex'}")
    else:
        print(
            "note: results/wikidata_case_study.json not found; case-study table not "
            "regenerated (run scripts/wikidata_case_study_benchmark.py).",
        )
    (TABLES_DIR / "wikidata_case_study_macros.tex").write_text(
        generate_wikidata_case_study_macros()
    )
    print(f"Wrote {TABLES_DIR / 'wikidata_case_study_macros.tex'}")

    if REPRO_PATH.exists():
        repro = json.loads(REPRO_PATH.read_text())
        GENERATED_DIR.mkdir(parents=True, exist_ok=True)
        (GENERATED_DIR / "reproducibility.tex").write_text(generate_reproducibility_macros(repro))
        print(f"Wrote {GENERATED_DIR / 'reproducibility.tex'}")
    else:
        print(f"warning: {REPRO_PATH} not found; reproducibility macros not regenerated.", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
